### PR TITLE
update chat SDK to version alias

### PR DESCRIPTION
**Pull request by scarroll32**
Resolves https://github.com/TwilioDevEd/sdk-starter-ruby/issues/2

### CODE REVIEW

**Comment by scarroll32** [comment]
The sample code only works when the channel already exists. The ```chatClient.getChannelByUniqueName``` method returns a 404 and the code crashes if the channel cannot be found. The sample code implies it will return a null or false.

Have corrected the sample code so that it runs, but will also log this issue with Twilio as the current behaviour is not optimal.

The 404 issue has been logged directly with Twilio, ticket number 889936 for any Twilio staff reading this.

**Comment by jefflinwood** [comment]
Thanks - there is some work I need to do around updating the Chat SDK, and in particular, the way channels are retrieved has changed with the latest version of the Chat SDK.

Thanks for your contribution!

**Comment by a-rank** [comment]
Hi! I'm engineer from Programmable Chat team, 
version 0.11.0 of javascript SDK has a bug which prevents from using getChannelByUniqueName(), this patch is for updating from 0.11.0 to a latest hotfix of 0.11. 

@jefflinwood is it possible to make this change? 

Thanks!

**Comment by scarroll32** [comment]
Hi @a-rank a quick question: I do understand that chat is in beta, but if possible I'd like to control when changes are made to the libraries. If we use:

```javascript
<script src="///media.twiliocdn.com/sdk/js/chat/v0.11/twilio-chat.js"></script>
```

Can the contents of the library change without changing the v0.11 ? 

ie: can I lock my code to use a specific version of the Twilio js library?

Great sample code by the way - was helpful in building our app.

**Comment by a-rank** [comment]
@seanfcarroll you can lock into 
<script src="///media.twiliocdn.com/sdk/js/chat/releases/0.11.1/twilio-chat.min.js">, no problems. 0.11.1 is the last release for 0.11, but I'd suggest to upgrade into latest, 0.12

**Comment by jefflinwood** [comment]
Hi,  I can switch the code to use this:

`<script src="///media.twiliocdn.com/sdk/js/chat/v0.11/twilio-chat.js"></script>`

Instead of the specific .0 release. I'll make that change in another PR.

**Comment by jefflinwood** [comment]
Hi, I just created another PR (on all of the SDK Starter Kits) and merged it with the changes - Thanks @seanfcarroll !

https://github.com/TwilioDevEd/sdk-starter-ruby/pull/7

**Comment by a-rank** [comment]
thanks @jefflinwood

**Pull request closed without merging**
